#! /usr/bin/env python3
import argparse
import pandas as pd
from scipy.stats import stats
import sys

# this code outputs latex table.
# use the following to convert it to markdown.
# pandoc -s tbl2017.tex -t markdown+grid_tables-simple_tables -o tbl2017.md

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("-r", help="list of json evaluation files", type=str, nargs="+")
    parser.add_argument("-m", help="which measures in the evaluation file to tablify", type=str, nargs="+")
    parser.add_argument("-a", help="alpha value of t-test", type=float, default=0.05)
    parser.add_argument("-x",
                        help="compute statistical significance between [all] rows, only [one row (specify the row)]",
                        type=str)
    args = parser.parse_args()
    evals = {}
    for e in args.r:
        with open(e, "r") as f:
            name = e.replace("_", "-")
            evals[name] = pd.read_json(f).T
            evals[name][evals[name] <= -0] = 0

    # sys.stderr.write("{} {}\n".format(evals.keys(), args.x))

    d = pd.DataFrame()
    t = pd.concat([x.mean() for x in evals.values()], axis=1)
    t.columns = evals.keys()
    df = t.T
    df2 = t.T
    strs = []
    s = {}
    for x in df:
        for i in df[x].index:
            p = 0.0
            if len(args.x) > 0 and args.x != "all":
                p = stats.ttest_rel(evals[i][x], evals[args.x][x]).pvalue
                if x + i not in s:
                    s[x + i] = []
                if p < args.a:
                    s[x + i].append('*')
            if len(args.x) > 0 and args.x == "all":
                for k, j in enumerate(df[x].index):
                    if i == j:
                        continue
                    if i + j + x in strs:
                        continue
                    p = stats.ttest_rel(evals[i][x], evals[j][x]).pvalue
                    if p < args.a:
                        if x + i not in s:
                            s[x + i] = []
                        s[x + i].append(str(k + 1))
                    strs.append(i + j + x)
    for x in df:
        for i in df[x].index:
            if x + i in s:
                df2[x][i] = "{:.4f}".format(df[x][i]) + "$^{" + ",".join(s[x + i]) + "}$"
    print(df2[args.m].to_latex(escape=False))
